### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by hettiger** [hettiger/larapress#31]
Do some refactoring so it is possible to provide hassle free updates.  
Add some information on that in the introduction.md docs file

**Comment by gayanhewa** [comment]
Lets break down this task I can spend a few hours with this.

**Comment by hettiger** [comment]
gayanhewa well theres only language files missing that should go into the Larapress directory thought. I think we can leave the larapress config in the main config dir for good. One thing that really makes me think is if i should make the complete thing a package itself at first. What do you think about that?

**Comment by gayanhewa** [comment]
Well packaging the whole thing is a good idea. There will be a lot of use cases where people would use it on existing application. But we will have to plan for all the features. I guess you are already having a vision as to where you would see this being used by a majority. According to that we can move forward the packaging.

**Comment by hettiger** [comment]
I'll make it a package thought :-)
But for today, I wont do any coding, wrote my last exam today and I'm feeling really tired of all the learning in the past days. There are more commits to expect of me tomorrow ;-)

**Comment by hettiger** [comment]
I'm facing some trouble with Travis testing. If you're familiar with that and still want to help you might have a look at #32

**Comment by hettiger** [comment]
#32 got delayed. Too much hassle for now and I want to move forward. Travis and Scrutinizer setup needs to be working properly so contributions wont be too difficult to manage.

**Comment by hettiger** [comment]
I want to release v0.0.9 so this will be closed. This task will be split up into several parts for the next versions. The final goal is to make the whole cms a composer package.
